#!/bin/ash

build() {
    # add_module "squashfs"
    # add_module "overlay"
    add_runscript
}

help() {
    cat <<HELPEOF
    This hook moves a squashfs filesystem to a ramdisk and mounts it as the root filesystem.
HELPEOF
}
