#!/bin/ash

build() {
    add_module "zram"
    add_binary "/usr/bin/unsquashfs"
    add_binary "/usr/bin/zramctl"
    add_binary mkfs.ext4
    add_runscript
}

help() {
    cat <<HELPEOF
    This hook moves a squashfs filesystem to a ramdisk and mounts it as the root filesystem.
HELPEOF
}
