#!/bin/sh

build() {
    add_module "squashfs"
    add_module "overlay"
    add_module "zram"
    add_binary "/usr/bin/zramctl"
    add_binary "/usr/bin/mkswap"
    add_binary "/usr/bin/swapon"
    add_runscript
}

help() {
    cat <<HELPEOF
    This hook moves a squashfs filesystem to a ramdisk and mounts it as the root filesystem.
HELPEOF
}
