#!/bin/ash

run_hook() {
    mkdir -p /mnt/stuff
    mount PARTUUID="part-uuid" /mnt/stuff

    modprobe zram

    mkdir -p /squash_root
    zramctl /dev/zram0 --algorithm zstd --size ramdisk-size
    mkfs.ext4 /dev/zram0
    mount /dev/zram0 /squash_root

    unsquashfs -d /squash_root /mnt/stuff/squashfs/squash-name.sfs
    mkdir -p /squash_root/proc /squash_root/sys /squash_root/dev /squash_root/run /squash_root/tmp
    sync
    umount /squash_root
    umount /mnt/stuff

    squash_mount() {
        mount "/dev/zram0" "$1"
    }
    mount_handler=squash_mount
}
